### ISSUE TITLE
Sign in with Google does not work

### ISSUE THREAD

**Issue by chrisatomix** [rfgamaral/SlackUI#11]
We have Google Apps authentication enabled (forced) for all our team, so unfortunately we can't test this app.
Clicking "Sign in with Google" simply opens a browser window, which eventually takes you to Slack directly. The SlackUI app remains at the login screen.
![clipboard01](https://cloud.githubusercontent.com/assets/1768449/5994585/1003bf54-aaca-11e4-82e2-f4fd5567a31c.png)
Unfortunately this is probably a non-trivial thing to implement in a standalone app, Google Authentication could be quite a challenge (in some desktop apps they have to start a server listening on localhost to detect login callbacks). But I figured I'd create an Issue anyway if someone has any ideas.
(Feel free to close and flag as "WONTFIX")

**Comment by rfgamaral** [comment]
Can you please confirm if it's the same issue as #3 or somewhat different?

**Comment by chrisatomix** [comment]
Sorry, I somehow completely missed that issue (I must have only search for "google" rather than "oauth"). 
I'll close this now and follow #3 for updates. Thanks!

**Comment by rfgamaral** [comment]
@chrisatomix Could you possibly compile the latest version yourself and see if the problem is fixed for you? I believe this was also fixed when #8 was fixed.

I tested it on my end and I was able to sign-in with my Google account. I'm just curious if also fixes the use case described at #3 (sign-in » google » active directory » slack), but @bartoncasey doesn't seem to reply back anymore.

**Comment by chrisatomix** [comment]
Unfortunately I have no idea how to compile this, I'm a PHP developer.

**Comment by rfgamaral** [comment]
I'm gonna try and build a new version tomorrow. It's 4am here, I need to get some sleep :zzz:.

**Comment by chrisatomix** [comment]
That would be great, thanks!

**Comment by chrisatomix** [comment]
Any update on a new build? The last release was in December, and I have no way of compiling from source to be able to test this.
Thanks again!

**Comment by rfgamaral** [comment]
Sorry, I was trying to get the multiple team support done before getting a release out. If you give me your e-mail, I'll send you pre-release version with this issue [possibly] fixed. What architecture do you use, x86 or x64?

**Comment by chrisatomix** [comment]
I'm Win7 x64, and my email is chris@atomix.com.au

Thanks!

**Comment by rfgamaral** [comment]
E-mail being sent... Give it a few minutes, it's 36,4MB and I have a really bad upload :(

**Comment by chrisatomix** [comment]
Strange, it's been 3 hours and nothing has come through yet. Did you attach the file to the email or just send me a link to it? Nothing in my spam folder either.

**Comment by rfgamaral** [comment]
I noticed now that the e-mail was not sent, maybe a file size limit on Gmail? Not sure... Anyway, sent you another e-mail with a link. Sorry about that.

**Comment by chrisatomix** [comment]
Works perfectly! I'm using it with Google Authenticator (two-factor authentication), and it had no issues. Thanks again!
