### ISSUE TITLE
Run and I get nothing

### ISSUE THREAD

**Issue by gemmell** [rfgamaral/SlackUI#12]
Builds fine, but nothing comes up when I run the app. If I just double click the exe in windows explorer nothing is shown but the exe is running in task manager. If I step through it gets to the Application.Run(new NotificationContext());
and then nothing....
I'm a C++ guy not a .NET guy so I really don't know how to debug this.

**Comment by MichaelAllenMiller** [comment]
Have you checked your notification bar?

**Comment by rfgamaral** [comment]
Yes, it starts hidden. And since it's a new icon in the notification area, Windows will automatically hide it after a little while. Please click the little white arrow and the SlackUI icon should be there.

Let us know if this solved it for you.

**Comment by Ladefuss** [comment]
This was the only snag i ran into when running this the first time (until i found this issue). You might want to consider implementing some sort of notification popup from notification bar on start. 

So far it's been a pleasure using this application compared to always having a browser pane reserved for Slack. I will continue evaluating and return with feedback. 

Thankyou for releasing SlackUI

**Comment by gemmell** [comment]
Yeh, that was it. 

Would like it if we could have tabs with different slack teams...

**Comment by rfgamaral** [comment]
I'll add support for different teams (follow #5 to keep up with that) but tabbed browsing is not planned for the time being. I'll close this then :)

**Comment by rfgamaral** [comment]
@Ladefuss 
Sorry, missed your comment.

Yeah, you're probably right. I'm going to consider that :)
