### ISSUE TITLE
Text area focus

### ISSUE THREAD

**Issue by mklaber** [rfgamaral/SlackUI#14]
It'd be great if, upon returning window focus to SlackUI, the text input cursor was in the place it was when SlackUI lost focus. Failing that, it'd be great if it were always in the message entry box. (I looked at the source code and at https://github.com/cefsharp/CefSharp and couldn't figure out how that'd be done mostly because I couldn't really figure out how CefSharp works.)

Steps to reproduce:

1. Open Notepad
2. Open SlackUI
3. Send a message in SlackUI to a friend/slackbot
4. `ALT`+`TAB` to Notepad
5. `ALT`+`TAB` back to SlackUI

At this point, the text input cursor is no where to be found.

**Comment by rfgamaral** [comment]
I'm not really sure SlackUI can have control over that, maybe it's something CefSharp needs to do by itself? Not sure, need to check with CefSharp guys.

**Comment by mklaber** [comment]
I suspect you could at least do the second option (always focus to message entry box) with some javascript (but just can't really figure out how to 1) run javascript on demand, and 2) listen to window focus to know when to run javascript). If you point me to some code snippets or CefSharp reference that actually demonstrates calling js (couldn't find any...), I'm happy to give it a whirl.

**Comment by MichaelAllenMiller** [comment]
All that should be needed is to give the ChromiumWebBrowser control focus.  I implemented this in [my fork](https://github.com/MichaelAllenMiller/SlackUI/), but I'm afraid it has diverged much too much to submit a pull request.

**Comment by rfgamaral** [comment]
@MichaelAllenMiller Even though you diverged much (as you say), the PR says "This pull request can be automatically merged". So I believe this can still be merged without an issue?

**Comment by MichaelAllenMiller** [comment]
Yes, I went ahead and did the same fix on your master and submitted that.  You should be able to merge it without issue.

**Comment by rfgamaral** [comment]
Fixed at cb8d348293e9aa02666aaab3dd7fe4e1bc8b2c3a. Thanks @MichaelAllenMiller.
