### ISSUE TITLE
Adapt to Windows DPI settings

### ISSUE THREAD

**Issue by tkiapril** [rfgamaral/SlackUI#18]
![untitled](https://cloud.githubusercontent.com/assets/7963440/6207049/82e4d230-b5db-11e4-8741-dada04171532.png)

I use 125% DPI settings from Control Panel\Appearance and Personalization\Display.
As you can see, from this settings SlackUI does not adapt to the resolution and thus, portions of webpage gets cut off.
Although after some resizing it gets normal, but it would be great if some workaround could be made.

**Comment by rfgamaral** [comment]
I will need to investigate this.

Just one question though... Do you use 125% DPI all the time or do you change the DPI setting from time to time?

**Comment by tkiapril** [comment]
I use 125% all the time, and my secondary laptop was also shipped factory with those settings. Maybe the industry is slowly changing to do so?
