### ISSUE TITLE
Custom resource handler sometimes fails to download CSS

### ISSUE THREAD

**Issue by rfgamaral** [rfgamaral/SlackUI#22]
I don't know if I'm the only one with this problem but I've noticed that the custom resource handler sometimes (it doesn't happen all the time) fails to [manually download](https://github.com/rfgamaral/SlackUI/blob/master/SlackUI/Handlers/BrowserResourceHandler.cs#L39) the CSS; and an exception was thrown and the application crashed.

I tried to avoid that and [retry to download the CSS at least 3 times](accd9197ab4ed16ac169226f8042ce8d79f4ff7a) before giving up and just display the page without it (not ideal). It still failed sometimes and in a future commit I increased the wait time between requests from 250ms to 500ms. It still doesn't solve the problem... Sometimes the CSS still fails and this is very annoying.

To work around this issue I added a [reload team site](fae08699db869436d67799f30d82d1779ee35066) option to the right-click system menu, but this is still cumbersome.

Does this happen with anyone else or just me? Let me know if it happens with you too...

Does anyone have any idea on how to improve the CSS resource loading without failing from time to time?

**Comment by MichaelAllenMiller** [comment]
I haven't noticed it before. I'll try to look in to it when I get some time.

**Comment by rfgamaral** [comment]
Well, my Internet connection has been very unstable for the past few weeks, maybe that's the cause for this...

**Comment by rfgamaral** [comment]
It seems I'm the only one with this issue and it hasn't happened as of late so I'm closing it.
