### ISSUE TITLE
Focus in text box lost on window focus

### ISSUE THREAD

**Issue by jaraco** [rfgamaral/SlackUI#24]
If I'm in a text box on a web site (such as this one), and I take the focus away from the window and then bring it back, the browser will return the focus to the text box so I may resume typing.

In the SlackUI, however, when returning to the application, even if the cursor was in the text box when focus was lost, the focus does not return to the typing box, so one must click into the text box to resume typing. It would be nice if the focus could return.

**Comment by rfgamaral** [comment]
What version are you using? Please check in the about box (right-click the SlackUI icon).

I'm asking this because this issue was [supposedly] fixed in cb8d348293e9aa02666aaab3dd7fe4e1bc8b2c3a and is part of the latest binary release.

**Comment by jaraco** [comment]
1.0.14360

**Comment by jaraco** [comment]
Yep. Fixed in 1.1.15053.
