### ISSUE TITLE
Add an option to hide the "Show DevTools"

### ISSUE THREAD

**Issue by joeyespo** [rfgamaral/SlackUI#25]
![image](https://cloud.githubusercontent.com/assets/634573/6581669/eee49286-c72e-11e4-8898-2445cbe555c1.png)

This isn't something end-users will necessarily use. Can this go in the settings defaulted to False?

Related, can the "Reload Team Site" also be hidden with that setting or move to the Notify Icon menu? The underlying reason for that is the system menu shouldn't really be changed.

I can implement this if you like, but I read that you'd rather someone create an issue first. Thanks for putting in the time to maintain this!

**Comment by rfgamaral** [comment]
This is the intended behavior and it will remain as such for the time being.

> This isn't something end-users will necessarily use.

Agree. But "normal" users or "normal" usage of SlackUI doesn't require users to open the system menu at all. Those options are specifically in the system menu for that reason. They are intended for advanced users debugging/tinkering (devtools) and "just in case" (reload team site).

**Comment by joeyespo** [comment]
Ok.

> But "normal" users or "normal" usage of SlackUI doesn't require users to open the system menu at all.

The Chrome extension does. The system menu is useful for closing windows, etc.

**Comment by rfgamaral** [comment]
I don't understand the chrome extension relevance. What do you mean with that?

Why would you close a window from the system menu? Don't you have jump lists when right-clicking the taskbar button? You need to explicitly press Shift first...

**Comment by joeyespo** [comment]
Ohhh, ha. I totally forgot that I tweaked Windows a while back to make it behave differently. Looks like I'm the exception here afterall. Carry on :-) 

Keep in mind, the system menu can still be accessed from clicking the top-left icon, so it's not entirely invisible to end-users.

**Comment by rfgamaral** [comment]
I know it's not invisible, I actually always access it through the top-left icon myself. But "normal" users will not likely open that specific menu. That's why I placed them in that menu in the first place, they are for  "advanced " used.

**Comment by rfgamaral** [comment]
Thanks for your input :)
