### ISSUE TITLE
Soundcloud Inline Preview opens in new window instead of Inline

### ISSUE THREAD

**Issue by kaichi** [rfgamaral/SlackUI#8]
To recreate this, simple paste a Soundcloud link into the channel.

For example: https://soundcloud.com/flume/disclosure-you-me-flume-remix

The inline preview loads, but the embedded element to play the music opens in my Firefox browser, the URL below.

https://w.soundcloud.com/player/?visual=true&url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F96379023&show_artwork=true&maxheight=150

That should be embedded inline in the Slack channel.

**Comment by rfgamaral** [comment]
I'm a little short on time to debug this issue but this is either:

- A bug within SlackUI handling of URls.
- A bug on CefSharp (not likely).
- CefSharp can't handle Soundcloud previews.
- Something is missing from my CefSharp binaries.

**Comment by rfgamaral** [comment]
Hopefully the fix needed for this won't introduce any kind of regression bug. I'm not going to make a new release just for this fix. Please compile your own version if you need this fix that bad.

Thank you for collaboration :)
